// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmu725y8CnyIBuuJZziRPSJd0Z4EVSZ6Q',
    appId: '1:907003888549:web:50609ca5a2693e1b375e4c',
    messagingSenderId: '907003888549',
    projectId: 'socialnetwork-fe3dd',
    authDomain: 'socialnetwork-fe3dd.firebaseapp.com',
    storageBucket: 'socialnetwork-fe3dd.firebasestorage.app',
    measurementId: 'G-S022M3SVGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbn1YO2etP-pAA3jPQJcYQNlX8hNFE_Do',
    appId: '1:907003888549:android:dbabb32b587946cc375e4c',
    messagingSenderId: '907003888549',
    projectId: 'socialnetwork-fe3dd',
    storageBucket: 'socialnetwork-fe3dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7zTIVJzMgnxksrOEnW4I1LJNx0S_4Rh4',
    appId: '1:907003888549:ios:b4edcb91e4a7321c375e4c',
    messagingSenderId: '907003888549',
    projectId: 'socialnetwork-fe3dd',
    storageBucket: 'socialnetwork-fe3dd.firebasestorage.app',
    iosBundleId: 'com.example.socialnetwork1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7zTIVJzMgnxksrOEnW4I1LJNx0S_4Rh4',
    appId: '1:907003888549:ios:b4edcb91e4a7321c375e4c',
    messagingSenderId: '907003888549',
    projectId: 'socialnetwork-fe3dd',
    storageBucket: 'socialnetwork-fe3dd.firebasestorage.app',
    iosBundleId: 'com.example.socialnetwork1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmu725y8CnyIBuuJZziRPSJd0Z4EVSZ6Q',
    appId: '1:907003888549:web:b23ad2b8e16af99c375e4c',
    messagingSenderId: '907003888549',
    projectId: 'socialnetwork-fe3dd',
    authDomain: 'socialnetwork-fe3dd.firebaseapp.com',
    storageBucket: 'socialnetwork-fe3dd.firebasestorage.app',
    measurementId: 'G-FJKR65S2LG',
  );

}