// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3smFhdT2XGmb7BhsIjK1zmJ0U6FCp3c8',
    appId: '1:903187015707:web:61928d5552d030115130be',
    messagingSenderId: '903187015707',
    projectId: 'deksombun-9eba1',
    authDomain: 'deksombun-9eba1.firebaseapp.com',
    storageBucket: 'deksombun-9eba1.firebasestorage.app',
    measurementId: 'G-L66RRCXYQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDud0saTz_GyhiSglX5ABNLVqA_KS66Vzk',
    appId: '1:903187015707:android:d093117a60ab414f5130be',
    messagingSenderId: '903187015707',
    projectId: 'deksombun-9eba1',
    storageBucket: 'deksombun-9eba1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWjJGKUmVVNgYCv0Lr53xJRtYOGwFhnP8',
    appId: '1:903187015707:ios:d43e9532f593a8705130be',
    messagingSenderId: '903187015707',
    projectId: 'deksombun-9eba1',
    storageBucket: 'deksombun-9eba1.firebasestorage.app',
    iosBundleId: 'com.example.socialnetwork1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWjJGKUmVVNgYCv0Lr53xJRtYOGwFhnP8',
    appId: '1:903187015707:ios:d43e9532f593a8705130be',
    messagingSenderId: '903187015707',
    projectId: 'deksombun-9eba1',
    storageBucket: 'deksombun-9eba1.firebasestorage.app',
    iosBundleId: 'com.example.socialnetwork1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3smFhdT2XGmb7BhsIjK1zmJ0U6FCp3c8',
    appId: '1:903187015707:web:7939adf28ed8af945130be',
    messagingSenderId: '903187015707',
    projectId: 'deksombun-9eba1',
    authDomain: 'deksombun-9eba1.firebaseapp.com',
    storageBucket: 'deksombun-9eba1.firebasestorage.app',
    measurementId: 'G-LXR6ZPV2E6',
  );

}